version: '3'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    ports:
      - "5000:5000"
      - "9600:9600"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      config.reload.automatic: "true"
      http.host: "0.0.0.0"
      log.format: "plain"
      log.level: "info"
      pipeline.batch.delay: 10
      pipeline.batch.size: 250
      pipeline.unsafe_shutdown: "true"
      pipeline.workers: 4
      xpack.monitoring.elasticsearch.password: "changeme"
      xpack.monitoring.elasticsearch.url: "http://elasticsearch:9200"
      xpack.monitoring.elasticsearch.username: "logstash_system"
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
    depends_on: 
      - elasticsearch
    networks:
      - elk
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
      xpack.security.enabled: "false"
    networks: 
      - elk
  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - "5601:5601"
    environment:
      xpack.monitoring.elasticsearch.password: "changeme"
      xpack.monitoring.elasticsearch.url: "http://elasticsearch:9200"
      xpack.monitoring.elasticsearch.username: "logstash_system"
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
    depends_on: 
      - elasticsearch
    networks:
      - elk
    
networks:
  elk:
    driver: bridge